# Generated by Django 4.1.7 on 2023-03-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('p', 'Personal'), ('b', 'Business')], default='p', max_length=2, null=True),
        ),
    ]
