# Generated by Django 4.1.7 on 2023-04-03 07:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stream.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Device Name')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=255, unique=True, verbose_name='Serial Number')),
                ('mac_address', models.CharField(max_length=100, unique=True, verbose_name='Mac Address')),
                ('imei', models.CharField(max_length=100, unique=True, verbose_name='IMEI Address')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(1)])),
                ('category', models.CharField(choices=[('phone', 'Phone'), ('computer', 'Computer'), ('tablet', 'Tablet'), ('accessory', 'Accessory'), ('others', 'Others')], default='phone', max_length=50)),
                ('desc', models.TextField(verbose_name='Device Description')),
                ('quality', models.PositiveIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'New')], default=2, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('stolen', 'Stolen'), ('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='device/images/', validators=[stream.validators.validate_file_size])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stream.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFirstAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stream.device')),
                ('first_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
