# Generated by Django 4.1.7 on 2023-04-03 07:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(default=1, help_text='Warranty in days', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1100)], verbose_name='Warranty Life')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.device')),
            ],
        ),
    ]
