# Generated by Django 4.2 on 2023-04-05 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0005_pendingtransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransfer',
            name='transferor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pending_transferors', to=settings.AUTH_USER_MODEL),
        ),
    ]
