# Generated by Django 4.2 on 2023-04-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_alter_pendingtransfer_transferor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='stream.device'),
        ),
    ]
