# Generated by Django 4.2 on 2023-04-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_reset_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reset',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
