# Generated by Django 4.2 on 2023-04-17 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_reset_token_alter_usertoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text="Phone number must be exactly 10 digits and start with '07'", max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^07\\d{8}$', 'Phone number must be exactly 10 digits and must be a rwandan Number.')]),
        ),
    ]
